module.exports = {
	Adverts: require('./Adverts.js'),
	Analytics: require('./Analytics.js'),
	AnimatedGameObject: require('./AnimatedGameObject.js'),
	AssetLoader: require('./AssetLoader.js'),
	Audio: require('./Audio.js'),
	Button: require('./Button.js'),
	ContainerObject: require('./ContainerObject.js'),
	Easing: require('./Easing.js'),
	EventHandler: require('./EventHandler.js'),
	FBInstant: require('./FBInstant.js'),
	Leaderboards: require('./FBLeaderboards.js'),
	GameObject: require('./GameObject.js'),
	GenericDialog: require('./GenericDialog.js'),
	GameSparks: require('./GSModule.js'),
	MiscPolyfills: require('./MiscPolyfills.js'),
	NineSliceObject: require('./NineSliceObject.js'),
	SaveData: require('./SaveData.js'),
	Text: require('./Text.js'),
	ToggleButton: require('./ToggleButton.js'),
	Token: require('./Token.js'),
};